# Generated by Django 2.1.7 on 2019-02-21 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('destination', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plan', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
